name: itizapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.0+4
  dio: ^5.2.1+1
  equatable: ^2.0.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  shared_preferences: ^2.2.3
  firebase_database: ^10.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.2
  flutter_svg: ^1.1.1
  google_fonts: ^5.1.0
  http: ^1.1.0
  logger: ^1.0.0
  sizer: ^2.0.15
  path: ^1.9.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/boton_itiz.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"

flutter:
  uses-material-design: true
  

  assets:
    - assets/images/
    - assets/icons/
    - assets/icon/
    - .env
